### ISSUE TITLE
Changing learning rate crashes actor_critic_agent.py

### ISSUE THREAD

**Issue by Ynjxsjmh** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#12] opened 2021-03-15 04:33 UTC
https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/aad22c1c121fa4af41818d26880b1fc6903265b6/Chapter02/8_actor_critic_agent.py#L37

Change the learning rate above to `1e-1` and run the edited file, after some episodes, it will throw the error:

```
Traceback (most recent call last):
  File "8_actor_critic_agent.py", line 108, in <module>
    train(agent, env, num_episodes)
  File "8_actor_critic_agent.py", line 91, in train
    next_state, reward, done, _ = env.step(action)
  File "~/.pyenv/versions/tf2/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "~/.pyenv/versions/tf2/lib/python3.6/site-packages/gym/envs/classic_control/cartpole.py", line 104, in step
    assert self.action_space.contains(action), err_msg
AssertionError: 2 (<class 'int'>) invalid
```

**Comment by praveen-palanisamy** [comment] 2021-03-17 22:26
Hi @Ynjxsjmh ,
The reason you get that error from the CartPole environment is because the action logits predicted by the neural-network based Actor in [this line](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/aad22c1c121fa4af41818d26880b1fc6903265b6/Chapter02/8_actor_critic_agent.py#L41) is `NaN` (Not a number).

The cause for the `NaN` value is the very-high learning rate value which causes an explosion in gradients thereby driving the neural network's output to infinity/`NaN`.

Using such a high learning rate of `1e-1` is not recommended with the Adam optimizer.

To solve your issue, please use a lower learning rate.

**Comment by praveen-palanisamy** [comment] 2021-03-17 22:35
Closing this issue since this is not an issue with the Actor-Critic Agent recipe but rather with the choice of the learning rate hyper-parameter used.

**Closed by praveen-palanisamy** 2021-03-17 22:35 UTC
Labels: question
